### ISSUE TITLE
Unable to deploy private project with submodules

### ISSUE THREAD

**Issue by oliversalzburg** [Strider-CD/strider-git#14]
We have a private GitHub project where we use submodules in the dev branch, but not master.

Both branches are set up for deployment in Strider-CD.

Because the submodules only exist in the dev branch, but the master branch is cloned, I need to run `git submodule update --init` in a custom script. This will always fail, because no authentication data is available.

I figured I could patch strider-git to just pass `--branch` when cloning the repository. Then I realized, that [there is already support for this](https://github.com/Strider-CD/strider-git/blob/8819dbfd8bcf24ed4d22f306cded9d212cf7a51a/worker.js#L76) (also [here](https://github.com/Strider-CD/strider-git/blob/8819dbfd8bcf24ed4d22f306cded9d212cf7a51a/worker.js#L25)). However, `--branch` (or `-b`, as you've used it), isn't provided. Instead, a `checkout` is performed after the `clone`.

Why isn't `--branch` used as intended?

**Comment by JSHARP-** [comment]
I am having the issue where my private repo has private submodules. When I try and deploy it, it breaks on the prepare step with trying to clone the submodules. After reading this, I just want to make sure, is the solution to use ssh cloning? For that I have to use the git provider, correct?

**Comment by ramesh-actiknow** [comment]
****
