### ISSUE TITLE
Create new release to include gitane fix

### ISSUE THREAD

**Issue by mandoz** [Strider-CD/strider-git#31]
Hello,

Can you guys create a new release so it includes the fix from this PR: https://github.com/Strider-CD/strider-git/pull/30

Without that fix cloning repos with ssh doesn't work on the docker runner.

Thanks.

**Comment by mandoz** [comment]
@chriz2600 I believe the rest of the changes to the other repositories are already in the latest release of strider-CD and only this one needs to be updated, correct?

**Comment by knownasilya** [comment]
I've published strider-git 0.2.5 and if you reinstall strider you'll get that new module.
